#!/bin/sh
#
# Depends:
#  fakeroot
#  apt-get
#  wget
#  dpkg
#  virtualenv (duh)

set -e -u

me=${0##*/}

case $VIRTUAL_ENV in
 '')
    virtualenv=$1
    shift ;;
 *) virtualenv=$VIRTUAL_ENV ;;
esac

case $# in 0) set -- --help;; esac
case $1 in
 --help | -[h?] )
    cat <<____HERE
Syntax: $me [ virtualenv ] deb-packages ...
  Attempt to install the listed deb packages locally into the virtualenv.
  If \$VIRTUAL_ENV is set ${VIRTUAL_ENV+(currently '$VIRTUAL_ENV')}, use that
  instead of requiring an explicit virtualenv to be identified.

  THIS IS EXPERIMENTAL and only works for very simple libraries.  It will
  not run the package postinst scripts or otherwise perform any proper
  installation; the files in the deb are simply extracted into place.

____HERE
    exit 0 ;;
 -*)
    echo "$me: Unknown option '$1' -- aborting" >&2
    exit 1 ;;
esac

test -e "$virtualenv/bin/activate" ||
{ echo "$me: '$virtualenv' does not appear to be a virtualenv" >&2
  exit 2; }

dest=$virtualenv/virtualdebs
mkdir -p "$dest/x"

for package; do
    case $package in
     http://*.deb | https://*.deb | ftp://*.deb )
	wget -nv -nc -P "$dest" "$package" ;;
     *.deb )
        cp "$package" "$dest" ;;
     */* | -* | *.* )
        echo "$me: '$package' seems invalid -- skipping" >&2
	continue ;;
     *)
        fakeroot apt-get install -y --print-uris "$@" |
        sed -n "s!.*'\(http://[^' ]*\.deb\)'.*!\1!p" |
        xargs -r wget -nv -nc -P "$dest" ;;
    esac
    printf "# %s %i (%s)\n%s\n" "$USER" "$(date +%s)" "$(date)" \
	"$package" >>"$dest/transcript.txt"
done

for deb in "$dest"/*.deb; do
    test -e "$dest/.${deb#$dest/}" && continue
    dpkg -x "$deb" "$dest/x"
    touch "$dest/.${deb#$dest/}"
done

######## FIXME: quick and dirty; should support every possible architecture
# See https://wiki.debian.org/Multiarch/Tuples
multiarch_suffix="/$(uname -m)-linux-gnu"
test -d "$dest/x/usr/lib$multiarch_suffix" || multiarch_suffix=''

case :${LD_LIBRARY_PATH-}: in
 *:"$dest/x/lib${multiarch_suffix-}:$dest/x/usr/lib${multiarch_suffix-}":*) ;;
 *) echo "$me: \
Your LD_LIBRARY_PATH does not contain the virtualdebs lib directory.
${LD_LIBRARY_PATH+
Current value:
  $LD_LIBRARY_PATH
}
Perhaps add

  export LD_LIBRARY_PATH=$dest/x/lib${multiarch_suffix-}:$dest/x/usr/lib${multiarch_suffix-}${multiarch_suffix:+:$dest/x/lib:$dest/x/usr/lib}\${LD_LIBRARY_PATH+:\$LD_LIBRARY_PATH}

to the end of your $virtualenv/bin/activate script?" >&2 ;;
esac
